deployments:
  - name: app
    chart: kube/deployment
    class: small
    secrets:
      - vault: app
        path: secrets
  - name: db
    chart: bitnami/mysql
    class: small
    secrets:
      - vault: db
        path: auth
