version: 2.1

executors:
  coopctl:
    docker:
      - image: colabcoop/deploy:0.0.31
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

jobs:
  production:
    executor: coopctl
    environment:
      HELMFILE_ENVIRONMENT: production
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: true
      - run: coopctl deploy
  staging:
    executor: coopctl
    environment:
      HELMFILE_ENVIRONMENT: staging
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.6
          docker_layer_caching: true
      - run: coopctl deploy

workflows:
  deploy:
    jobs:
      - production:
          context: colab-kube-production
          filters:
            branches:
              only: production
      - staging:
          context: colab-kube-staging
          filters:
            branches:
              only: staging
