version: 2.1

executors:
  coopctl:
    docker:
      - image: colabcoop/coopernetzner-deploy:0.1.7
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

jobs:
  prod:
    executor: coopctl
    environment:
      HELMFILE_ENVIRONMENT: prod
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy staging Colab.coop site
          command: coopctl deploy
  stage:
    executor: coopctl
    environment:
      HELMFILE_ENVIRONMENT: stage
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy staging Colab.coop site
          command: coopctl deploy
  stage2:
    executor: coopctl
    environment:
      HELMFILE_ENVIRONMENT: stage
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy staging 2 Colab.coop site
          command: coopctl deploy

workflows:
   deploy:
     jobs:
       - prod:
           context: coopernetes-production
           filters:
             branches:
               only: master
       - stage:
           context: coopernetes-staging
           filters:
             branches:
               only: develop
       - stage2:
           context: coopernetzner-staging
           filters:
             branches:
               only: testing
