version: 2.1

executors:
  coopctl:
    docker:
      - image: colabcoop/coopernetes-deploy:0.8.0
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

jobs:
  production:
    executor: coopctl
    environment:
      HELMFILE_ENVIRONMENT: production
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy staging Colab.coop site
          command: coopctl deploy
  staging:
    executor: coopctl
    environment:
      HELMFILE_ENVIRONMENT: staging
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Deploy staging Colab.coop site
          command: coopctl deploy

workflows:
   deploy:
     jobs:
       - production:
           context: coopernetes-production
           filters:
             branches:
               only: develop
       - staging:
           context: coopernetes-staging
           filters:
             branches:
               only: develop
