version: 2.1

executors:
  operator:
    docker:
      - image: colabcoop/operator:0.0.218
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD

jobs:
  production:
    executor: operator
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Deploy to CoLab Kube Production
          command: deploy
          no_output_timeout: 30m
  staging:
    executor: operator
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: Deploy to CoLab Kube Staging
          command: deploy
          no_output_timeout: 30m

workflows:
  deploy:
    jobs:
      - production:
          context: colab-kube-production-v2
          filters:
            branches:
              only: production
      - staging:
          context: colab-kube-staging-v2
          filters:
            branches:
              only: staging
