repositories:
  - name: colab
    url: https://colab-coop.github.io/helm-charts/charts
environments:
  prod:
  stage:
releases:
  - name: colab-site
    namespace: colab-site
    chart: colab/http-server
    version: 0.0.10
    secrets: colab-site
    values:
      - ./values/env.yaml.gotmpl
      - ./values/{{.Environment.Name}}.yaml.gotmpl
