repositories:
- name: colab
  url: https://colab-coop.github.io/coopernetes/charts

releases:
  - name: basic-http-server
    namespace: colab-site
    chart: colab/basic-http-server
    version: 0.3.0
    values:
      - host: stage.colab.coop
      - image: {{ requiredEnv "DOCKER_TAG" }}
