repositories:
- name: colab
  url: https://colab-coop.github.io/helm-charts/charts

environments:
  prod:
  stage:

releases:
  - name: http-server
    namespace: colab-site
    chart: colab/http-server
    version: 0.0.4
    values:
      - ./values/{{ .Environment.Name }}.yaml.gotmpl
      - image:
          tag: "{{ requiredEnv "DOCKER_TAG" }}"
          port: 80
      - imageCredentials:
          username: "{{ requiredEnv "DOCKER_USER" }}"
          password: "{{ requiredEnv "DOCKER_PASSWORD" }}"
