repositories:
- name: colab
  url: https://colab-coop.github.io/coopernetes/charts

environments:
  production:
  - hosts:
      - site.coopernetes.colab.coop
  staging:
  - hosts:
      - stage.colab.coop
      - www.stage.colab.coop

releases:
  - name: basic-http-server
    namespace: colab-site
    chart: colab/basic-http-server
    version: 0.4.1
    values:
      - image:
          tag: {{ requiredEnv "DOCKER_TAG" }}
          port: 80
      - imageCredentials:
          username: {{ requiredEnv "DOCKER_USER" }}
          password: {{ requiredEnv "DOCKER_PASSWORD" }}
