repositories:
- name: colab
  url: https://colab-coop.github.io/coopernetes/charts

environments:
  prod:
  stage:

releases:
  - name: basic-http-server
    namespace: colab-site
    chart: colab/basic-http-server
    version: 0.4.1
    values:
      - ./values/{{ .Environment.Name }}.yaml.gotmpl
      - image:
          tag: TAG
          port: 80
      - imageCredentials:
          username: USER
          password: PASS
