repositories:
- name: colab
  url: https://colab-coop.github.io/coopernetes/charts

releases:
  - name: basic-http-server
    namespace: colab-site
    chart: colab/basic-http-server
    version: 0.3.0
    values:
      - host: stage.colab.coop
      - image:
          tag: {{ requiredEnv "DOCKER_TAG" }}
          port: 80
      - imageCredentials:
          username: {{ requiredEnv "DOCKER_USER" }}
          password: {{ requiredEnv "DOCKER_PASSWORD" }}
